//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoeMoeD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flie()
        {
            this.Id = 0;
            this.Name = "0";
            this.UserId = 0;
            this.FolderId = 0;
            this.Type = "0";
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public int FolderId { get; set; }
        public string Type { get; set; }
    
        public virtual User User { get; set; }
        public virtual Folder Folder { get; set; }
    }
}
